export default interface CarData {
    baalut: string,
    degem_cd: string,
    degem_manoa: string,
    degem_nm: string,
    horaat_rishum: any,
    kinuy_mishari: string,
    kvutzat_zihum: string,
    misgeret: string,
    mispar_rechev: number,
    mivchan_acharon_dt: string,
    moed_aliya_lakvish: string,
    ramat_eivzur_betihuty: any,
    ramat_gimur: string,
    rank: number,
    shnat_yitzur: string,
    sug_degem: string,
    sug_delek_nm: string,
    tokef_dt: string,
    tozeret_cd: string,
    tozeret_nm: string,
    tzeva_cd: string,
    tzeva_rechev: string,
    zmig_ahori: string,
    zmig_kidmi: string,
    _id: number
}